Bumped libbuildpack-dynatrace to 1.4.1
cloudfoundry/php-buildpack pull request #522
Opened 2021-07-14 09:43 UTC by arthfl

* A short explanation of the proposed change:
Bumped libbuildpack-dynatrace to 1.4.1 to include the networkzone parameter when downloading the OneAgent from the API
* An explanation of the use cases your change solves
This includes the networkzone parameter when downloading the OneAgent from the API
* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

2021-08-17 11:31 UTC, arthfl commented
Dear maintainers, any ETA on this?

2021-08-18 15:39 UTC, arjun024 requested changes

2021-08-18 15:39 UTC, arjun024 commented on src/php/integration/deploy_a_php_app_with_dynatrace_test.go
> +			createdServices = append(createdServices, serviceName)
What is `createdServices` here?

2021-08-24 22:46 UTC, merged

2021-08-24 22:49 UTC, arjun024 commented
I have made changes to your diff because (1) f-Strings are not supported in py 2.6 which is used for extensions in the php-buildpack and (2) the tests were expecting logs from libbuildpack-dynatrace instead of the extension. Please run the tests locally before submitting PRs, for quicker review by maintainers.

2021-08-25 06:52 UTC, arthfl commented
@arjun024  Thanks a lot :-)